# Generated by Django 2.0.7 on 2020-08-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Име за URL'),
            preserve_default=False,
        ),
    ]
