# Generated by Django 2.0.7 on 2020-08-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshowimage',
            options={'verbose_name': 'Снимка за началната страница', 'verbose_name_plural': 'Снимки за началната страница'},
        ),
    ]
