# Generated by Django 2.0.7 on 2020-08-28 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200827_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, verbose_name='Емейл')),
                ('message', models.TextField(verbose_name='Съобщение')),
                ('answered', models.BooleanField(default=False, verbose_name='Отговорено ли е')),
            ],
            options={
                'verbose_name': 'Запитване',
                'verbose_name_plural': 'Запитвания',
            },
        ),
    ]
